import { useMemo } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, Heart, Library, Music2, Play, Search, Settings2, Sparkles, Clock3 } from 'lucide-react'
import { useAuth } from '@/context/AuthContext'
import { useRecentlyPlayedStatus, usePlaylistsStatus, useLikedSongsStatus } from '@/hooks/useLibraryData'
import { useLocalSongs } from '@/lib/localMusicDb'
import { usePlayer } from '@/context/PlayerContext'

function TrackCard({ track, tracks, player }) { return <button onClick={()=>player.playTrack(track,tracks)} className="group text-left min-w-0"><div className="relative aspect-square rounded-2xl overflow-hidden bg-surface-highlight mb-3"><img src={track.thumbnail} alt="" className="w-full h-full object-cover"/><span className="absolute right-3 bottom-3 w-11 h-11 rounded-full bg-brand text-black grid place-items-center opacity-0 group-hover:opacity-100 group-focus:opacity-100 transition-all shadow-lg"><Play size={18} fill="currentColor"/></span></div><p className="font-bold text-sm truncate">{track.title}</p><p className="text-xs text-text-muted truncate mt-1">{track.artist || 'Unknown artist'}</p></button> }
function Quick({to,icon:Icon,title,text}) { return <Link to={to} className="sf-panel p-5 group hover:bg-white/[.07] transition"><div className="w-11 h-11 rounded-xl bg-brand/15 text-brand grid place-items-center mb-4"><Icon size={21}/></div><h3 className="font-black">{title}</h3><p className="text-xs text-text-muted mt-1">{text}</p><ArrowRight size={15} className="mt-4 text-text-subdued group-hover:text-white"/></Link> }
export default function Home(){ const {user,signIn}=useAuth(); const p=usePlayer(); const {data:recent=[],loading:recentLoading}=useRecentlyPlayedStatus(user?.uid,12); const {data:playlists=[]}=usePlaylistsStatus(user?.uid); const {data:liked=[]}=useLikedSongsStatus(user?.uid); const [localSongs]=useLocalSongs(); const mixes=useMemo(()=>recent.length?recent:liked.length?liked:localSongs,[recent,liked,localSongs]);
 return <div className="p-4 md:p-7 max-w-[1500px] mx-auto space-y-10">
  <section className="sf-hero p-7 md:p-12 overflow-hidden relative"><div className="absolute -right-20 -top-24 w-80 h-80 rounded-full bg-brand/20 blur-3xl"/><div className="relative max-w-3xl"><p className="text-brand text-xs font-black uppercase tracking-[.25em]">Music without limits</p><h1 className="text-4xl md:text-6xl font-black tracking-tight mt-3">Everything you love.<br/><span className="text-brand">One place.</span></h1><p className="text-text-muted mt-5 max-w-2xl leading-7">Spotifusion brings online music, your local collection, playlists, favorites, lyrics and a full-featured player into one responsive experience.</p><div className="flex flex-wrap gap-3 mt-7"><Link to="/search" className="inline-flex items-center gap-2 bg-brand text-black font-black px-6 py-3 rounded-full"><Search size={17}/> Search music</Link>{user?<Link to="/library" className="inline-flex items-center gap-2 bg-white/10 px-6 py-3 rounded-full font-bold hover:bg-white/15"><Library size={17}/> Your Library</Link>:<button onClick={signIn} className="bg-white text-black font-black px-6 py-3 rounded-full">Sign in with Google</button>}</div></div></section>
  <section><div className="flex items-end justify-between mb-4"><div><p className="text-xs text-brand font-black uppercase tracking-widest">Quick access</p><h2 className="text-2xl font-black mt-1">Your Spotifusion</h2></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Quick to="/search" icon={Search} title="Search" text="Songs, artists and albums"/><Quick to="/liked-songs" icon={Heart} title="Liked Songs" text={`${liked.length} saved tracks`}/><Quick to="/local-files" icon={Music2} title="Local Music" text={`${localSongs.length} tracks on device`}/><Quick to="/settings" icon={Settings2} title="Settings" text="Audio, playback and privacy"/></div></section>
  <section><div className="flex items-end justify-between mb-4"><div><p className="text-xs text-text-subdued uppercase tracking-widest font-bold">Keep listening</p><h2 className="text-2xl font-black mt-1">{recent.length?'Recently played':'Start listening'}</h2></div><Link to="/recently-played" className="text-sm font-bold text-text-muted hover:text-white">See all</Link></div>{recentLoading?<div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-5">{Array.from({length:6},(_,i)=><div key={i} className="skeleton aspect-square rounded-2xl"/>)}</div>:mixes.length?<div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-5">{mixes.slice(0,12).map(t=><TrackCard key={t.id} track={t} tracks={mixes} player={p}/>)}</div>:<div className="sf-panel p-10 text-center text-text-muted">Search for your first song and it will appear here.</div>}</section>
  <section><div className="flex items-center justify-between mb-4"><div><p className="text-xs text-text-subdued uppercase tracking-widest font-bold">Explore</p><h2 className="text-2xl font-black mt-1">More to discover</h2></div><Link to="/discover" className="text-sm font-bold text-text-muted hover:text-white">Discover</Link></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Quick to="/discover" icon={Sparkles} title="Discover Music" text="Jump into quick searches and new music"/><Quick to="/library" icon={Library} title={`${playlists.length} Playlists`} text="Build and organize your collection"/><Quick to="/recently-played" icon={Clock3} title="Listening history" text="Return to tracks you played recently"/></div></section>
 </div>
}
