import { useEffect, useMemo, useRef, useState } from 'react'
import { Search as SearchIcon, WifiOff, Clock, X, SearchX, RotateCw, Trash2, Disc3, UserRound, ListMusic, Radio, Music2 } from 'lucide-react'
import { useLocation, useNavigate } from 'react-router-dom'
import { searchMusicPage } from '@/lib/search'
import { useAuth } from '@/context/AuthContext'
import { useOnlineStatus } from '@/hooks/useOnlineStatus'
import TrackRow from '@/components/TrackRow'
import { SkeletonRowList } from '@/components/Skeleton'
import { getArtwork } from '@/lib/artwork'

const HISTORY_KEY='spotifusion:search-history:v3', CACHE_PREFIX='spotifusion:search-results:v6:', CACHE_TTL=60*60*1000
const CATEGORIES=[['all','All',SearchIcon],['songs','Songs',Music2],['albums','Albums',Disc3],['artists','Artists',UserRound],['playlists','Playlists',ListMusic],['jukebox','Jukebox',Radio]]
const clean=v=>String(v||'').trim().replace(/\s+/g,' ')
const cacheKey=(q,c)=>`${CACHE_PREFIX}${c}:${clean(q).toLowerCase()}`
function cacheRead(q,c){try{const x=JSON.parse(sessionStorage.getItem(cacheKey(q,c))||'null');return x&&Date.now()-x.time<CACHE_TTL?x:null}catch{return null}}
function cacheWrite(q,c,d){try{sessionStorage.setItem(cacheKey(q,c),JSON.stringify({...d,time:Date.now()}))}catch{}}
function historyRead(){try{const x=JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function historyAdd(q){const x=[q,...historyRead().filter(v=>v.toLowerCase()!==q.toLowerCase())].slice(0,100);try{localStorage.setItem(HISTORY_KEY,JSON.stringify(x))}catch{}return x}

function EntityCard({item}){const navigate=useNavigate();const type=item.resultType;const Icon=type==='artist'?UserRound:type==='album'?Disc3:type==='jukebox'?Radio:ListMusic;const id=item.browseId||item.id;const image=getArtwork(item,'large');const path=type==='artist'?`/artist/${encodeURIComponent(id)}`:type==='album'?`/album/${encodeURIComponent(id)}`:`/youtube-playlist/${encodeURIComponent(id)}`;return <button type="button" onClick={()=>navigate(path,{state:{name:item.title,artwork:image,browseId:id}})} className="sf-entity-card group text-left min-w-0"><div className="relative aspect-square overflow-hidden rounded-2xl bg-surface-highlight mb-3">{image?<img src={image} alt="" loading="lazy" className={`w-full h-full object-cover ${type==='artist'?'rounded-full':''}`}/>:<div className="w-full h-full grid place-items-center"><Icon size={34} className="text-text-subdued"/></div>}</div><p className="font-bold text-sm truncate">{item.title||'Untitled'}</p><p className="text-xs text-text-muted truncate mt-1">{item.subtitle||item.artist||type}</p></button>}

export default function SearchFixed(){
 const {user}=useAuth(),navigate=useNavigate(),location=useLocation(),online=useOnlineStatus();
 const params=useMemo(()=>new URLSearchParams(location.search),[location.search]); const urlQuery=clean(params.get('q')); const urlCategory=CATEGORIES.some(x=>x[0]===params.get('category'))?params.get('category'):'all';
 const [query,setQuery]=useState(urlQuery),[submitted,setSubmitted]=useState(urlQuery),[category,setCategory]=useState(urlCategory),[results,setResults]=useState(()=>cacheRead(urlQuery,urlCategory)?.results||[]),[page,setPage]=useState(()=>cacheRead(urlQuery,urlCategory)?.batch||0),[hasMore,setHasMore]=useState(()=>Boolean(cacheRead(urlQuery,urlCategory)?.hasMore)),[loading,setLoading]=useState(false),[loadingMore,setLoadingMore]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState(historyRead);
 const abortRef=useRef(null),requestId=useRef(0),moreRef=useRef(false),sentinelRef=useRef(null),latest=useRef({results:[],page:0,hasMore:false});
 useEffect(()=>{latest.current={results,page,hasMore}},[results,page,hasMore]);
 const groups=useMemo(()=>{const seen=new Set();const u=results.filter(x=>{const k=`${x?.resultType||'song'}:${x?.id||''}`;if(!x?.id||seen.has(k))return false;seen.add(k);return true});return{all:u,songs:u.filter(x=>!x.resultType||x.resultType==='song'),albums:u.filter(x=>x.resultType==='album'),artists:u.filter(x=>x.resultType==='artist'),playlists:u.filter(x=>x.resultType==='playlist'),jukebox:u.filter(x=>x.resultType==='jukebox'||x.resultType==='mix')}}},[results]);

 async function load(q,cat,b=1){q=clean(q);if(!user||q.length<2||!navigator.onLine)return;if(b===1){abortRef.current?.abort();const controller=new AbortController(),rid=++requestId.current;abortRef.current=controller;setLoading(true);setError('');try{const d=await searchMusicPage(q,{category:cat,batch:1,signal:controller.signal});if(controller.signal.aborted||rid!==requestId.current)return;const r=Array.isArray(d.results)?d.results:[];setResults(r);setPage(1);setHasMore(Boolean(d.hasMore));cacheWrite(q,cat,{results:r,batch:1,hasMore:Boolean(d.hasMore)})}catch(e){if(e?.name!=='AbortError'){setResults([]);setPage(0);setHasMore(false);setError(e?.message||'Unable to search right now.')}}finally{if(abortRef.current===controller)setLoading(false)}return}
  if(moreRef.current||!latest.current.hasMore)return;moreRef.current=true;setLoadingMore(true);try{const d=await searchMusicPage(q,{category:cat,batch:b});const incoming=Array.isArray(d.results)?d.results:[];const seen=new Set(latest.current.results.map(x=>`${x?.resultType||'song'}:${x?.id||''}`));const fresh=incoming.filter(x=>{const k=`${x?.resultType||'song'}:${x?.id||''}`;if(!x?.id||seen.has(k))return false;seen.add(k);return true});if(!fresh.length){setHasMore(false);return}const merged=[...latest.current.results,...fresh];setResults(merged);setPage(b);setHasMore(Boolean(d.hasMore));cacheWrite(q,cat,{results:merged,batch:b,hasMore:Boolean(d.hasMore)})}catch(e){setError(e?.message||'Unable to load more results.')}finally{moreRef.current=false;setLoadingMore(false)}}

 // URL is the single source of truth. It only resets state; loading happens in ONE effect below.
 useEffect(()=>{const cached=cacheRead(urlQuery,urlCategory);setQuery(urlQuery);setSubmitted(urlQuery);setCategory(urlCategory);setResults(cached?.results||[]);setPage(cached?.batch||0);setHasMore(Boolean(cached?.hasMore));setError('');if(!urlQuery){abortRef.current?.abort()}},[urlQuery,urlCategory]);
 useEffect(()=>{if(user&&submitted.length>=2&&page===0)load(submitted,category,1)},[user,submitted,category,page]);
 useEffect(()=>()=>abortRef.current?.abort(),[]);
 useEffect(()=>{const node=sentinelRef.current;if(!node||!submitted||!hasMore)return;const ob=new IntersectionObserver(es=>{if(es[0]?.isIntersecting&&!loading&&!loadingMore)load(submitted,category,latest.current.page+1)},{root:document.querySelector('main'),rootMargin:'900px'});ob.observe(node);return()=>ob.disconnect()},[submitted,category,hasMore,loading,loadingMore]);
 function submit(v=query,c=category){const q=clean(v);if(q.length<2){setError('Enter at least 2 characters to search.');return}setHistory(historyAdd(q));setQuery(q);setSubmitted(q);setResults([]);setPage(0);setHasMore(false);navigate(`/search?q=${encodeURIComponent(q)}&category=${c}`)}
 function chooseCategory(c){if(c===category)return;setResults([]);setPage(0);setHasMore(false);setError('');navigate(submitted?`/search?q=${encodeURIComponent(submitted)}&category=${c}`:`/search?category=${c}`)}
 function clear(){abortRef.current?.abort();++requestId.current;setQuery('');setSubmitted('');setResults([]);setPage(0);setHasMore(false);navigate('/search',{replace:true})}
 if(!user)return <div className="p-6 text-center pt-20"><SearchIcon size={42} className="mx-auto mb-4 text-text-subdued"/><h1 className="text-xl font-bold">Sign in to search</h1><button onClick={()=>navigate('/login')} className="sf-primary-button mt-6">Sign in</button></div>;
 const visible=groups[category]||[],label=(CATEGORIES.find(x=>x[0]===category)||[])[1]||'All';const suggestions=query?[...history].filter(x=>x.toLowerCase().includes(query.toLowerCase())).slice(0,6):[];
 return <div className="p-4 md:p-6 max-w-[1500px] mx-auto pb-36 min-w-0"><form onSubmit={e=>{e.preventDefault();submit()}} className="relative max-w-3xl mb-4"><SearchIcon size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-black"/><input value={query} onChange={e=>{setQuery(e.target.value);setError('')}} placeholder="What do you want to play?" className="w-full bg-white text-black rounded-full pl-11 pr-28 py-3.5 outline-none"/>{query&&<button type="button" onClick={clear} className="absolute right-24 top-1/2 -translate-y-1/2 text-gray-600 p-2"><X size={16}/></button>}<button type="submit" disabled={query.trim().length<2} className="absolute right-1 top-1/2 -translate-y-1/2 sf-search-button">Search</button></form>
 <div className="search-category-tabs">{CATEGORIES.map(([id,l,Icon])=><button key={id} type="button" onClick={()=>chooseCategory(id)} className={`search-category-tab ${category===id?'is-active':''}`}><Icon size={16}/>{l}</button>)}</div>
 {!online&&<div className="flex gap-2 items-center text-sm text-yellow-500 bg-yellow-500/10 rounded-xl p-3 mb-4"><WifiOff size={16}/>You're offline.</div>}
 {suggestions.length>0&&!loading&&<div className="flex flex-wrap gap-2 mb-5">{suggestions.map(x=><button key={x} type="button" onClick={()=>submit(x)} className="sf-history-chip"><SearchIcon size={12}/>{x}</button>)}</div>}
 {history.length>0&&!query&&<div className="mb-6"><div className="flex justify-between mb-2"><span className="text-sm font-semibold">Recent searches</span><button type="button" onClick={()=>{localStorage.removeItem(HISTORY_KEY);setHistory([])}} className="sf-ghost-button"><Trash2 size={14}/>Clear</button></div><div className="flex flex-wrap gap-2">{history.slice(0,10).map(x=><button type="button" key={x} onClick={()=>submit(x)} className="sf-history-chip"><Clock size={12}/>{x}</button>)}</div></div>}
 {loading&&<SkeletonRowList count={8}/>} {error&&!loading&&<div className="flex justify-between items-center gap-3 bg-red-500/10 text-red-300 rounded-xl p-3 mb-4"><span className="text-sm">{error}</span><button type="button" onClick={()=>load(submitted,category,1)} className="sf-ghost-button"><RotateCw size={14}/>Retry</button></div>}
 {!loading&&!error&&submitted&&page>0&&!visible.length&&<div className="text-center py-16 text-text-muted"><SearchX size={40} className="mx-auto mb-3"/><p>No {label.toLowerCase()} results for “{submitted}”.</p></div>}
 {visible.length>0&&<section><div className="flex items-end justify-between mb-4"><div><p className="text-xs text-brand uppercase tracking-widest font-bold">Search results</p><h2 className="text-2xl font-black">{label}</h2></div><span className="text-xs text-text-subdued">{visible.length} loaded</span></div>
 {category==='songs'&&<div className="space-y-1">{groups.songs.map((t,i)=><TrackRow key={t.id} track={t} index={i} contextTracks={groups.songs}/>)}</div>}
 {category==='all'&&<div className="space-y-8">{groups.artists.length>0&&<div><h3 className="text-lg font-bold mb-3">Artists</h3><div className="search-entity-grid">{groups.artists.map(x=><EntityCard key={x.id} item={x}/>)}</div></div>}{groups.albums.length>0&&<div><h3 className="text-lg font-bold mb-3">Albums</h3><div className="search-entity-grid">{groups.albums.map(x=><EntityCard key={x.id} item={x}/>)}</div></div>}{groups.songs.length>0&&<div><h3 className="text-lg font-bold mb-3">Songs</h3><div className="space-y-1">{groups.songs.map((t,i)=><TrackRow key={t.id} track={t} index={i} contextTracks={groups.songs}/>)}</div></div>}{groups.playlists.length>0&&<div><h3 className="text-lg font-bold mb-3">Playlists</h3><div className="search-entity-grid">{groups.playlists.map(x=><EntityCard key={x.id} item={x}/>)}</div></div>}</div>}
 {(category==='albums'||category==='artists'||category==='playlists'||category==='jukebox')&&<div className="search-entity-grid">{visible.map(x=><EntityCard key={x.id} item={x}/>)}</div>}
 <div ref={sentinelRef} className="h-8"/>{loadingMore&&<div className="text-center text-sm text-text-subdued py-5">Loading more…</div>}</section>}
 </div>
}
