package com.spotifusion.app

import android.Manifest
import android.app.DownloadManager
import android.content.Context
import android.content.pm.PackageManager
import android.graphics.BitmapFactory
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.view.Gravity
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLEncoder

/** Final AMOLED player: local library + live Spotifusion YouTube search/streaming. */
class FinalPlayerActivity : AppCompatActivity() {
    private val black=Color.rgb(6,6,10); private val card=Color.rgb(15,15,23); private val card2=Color.rgb(23,22,32)
    private val white=Color.rgb(246,244,252); private val muted=Color.rgb(151,146,166); private val violet=Color.rgb(123,81,251); private val border=Color.rgb(43,40,58)
    private lateinit var page:FrameLayout; private lateinit var miniTitle:TextView; private lateinit var miniArtist:TextView; private lateinit var miniPlay:TextView
    private lateinit var local:List<LocalTrack>; private val ui=Handler(Looper.getMainLooper()); private var searchText=""; private var sleep:Runnable?=null
    private fun dp(v:Int)=(v*resources.displayMetrics.density+.5f).toInt()
    private fun t(s:String,z:Float,c:Int=white,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;setTextColor(c);includeFontPadding=false;if(b)typeface=Typeface.DEFAULT_BOLD}
    private fun box(c:Int=card,r:Int=17,stroke:Boolean=false)=android.graphics.drawable.GradientDrawable().apply{setColor(c);cornerRadius=dp(r).toFloat();if(stroke)setStroke(dp(1),border)}
    private fun grad(r:Int=18)=android.graphics.drawable.GradientDrawable(android.graphics.drawable.GradientDrawable.Orientation.TL_BR,intArrayOf(Color.rgb(55,34,112),violet)).apply{cornerRadius=dp(r).toFloat()}
    override fun onCreate(b:Bundle?){super.onCreate(b);window.statusBarColor=black;window.navigationBarColor=black;requestAudio();PlaybackController.connect(this);local=runCatching{LocalMusicScanner.scan(this)}.getOrElse{emptyList()};build();home()}
    private fun requestAudio(){val p=if(Build.VERSION.SDK_INT>=33)Manifest.permission.READ_MEDIA_AUDIO else Manifest.permission.READ_EXTERNAL_STORAGE;if(ContextCompat.checkSelfPermission(this,p)!=PackageManager.PERMISSION_GRANTED)ActivityCompat.requestPermissions(this,arrayOf(p),44);if(Build.VERSION.SDK_INT>=33&&ContextCompat.checkSelfPermission(this,Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)ActivityCompat.requestPermissions(this,arrayOf(Manifest.permission.POST_NOTIFICATIONS),45)}
    private fun build(){val root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(black)};root.addView(header(),LinearLayout.LayoutParams(-1,dp(61)));page=FrameLayout(this);root.addView(page,LinearLayout.LayoutParams(-1,0,1f));root.addView(mini(),LinearLayout.LayoutParams(-1,dp(70)).apply{setMargins(dp(9),dp(5),dp(9),dp(5))});root.addView(nav(),LinearLayout.LayoutParams(-1,dp(63)).apply{setMargins(dp(8),0,dp(8),dp(5))});setContentView(root)}
    private fun header()=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;setPadding(dp(14),dp(7),dp(14),dp(4));addView(t("S",18f,Color.WHITE,true).apply{gravity=Gravity.CENTER;background=grad(11)},LinearLayout.LayoutParams(dp(36),dp(36)));addView(t("Spotifusion",18f,white,true).apply{setPadding(dp(10),0,0,0)},LinearLayout.LayoutParams(0,-1,1f));addView(t("⌕",25f,white,true).apply{gravity=Gravity.CENTER;background=box(card2,15,true);setOnClickListener{search()}},LinearLayout.LayoutParams(dp(44),dp(44)).apply{rightMargin=dp(7)});addView(t("⋮",24f,white,true).apply{gravity=Gravity.CENTER;background=box(card2,15,true);setOnClickListener{settings()}},LinearLayout.LayoutParams(dp(44),dp(44)))}
    private fun nav()=LinearLayout(this).apply{gravity=Gravity.CENTER;background=box(card,21,true);setPadding(dp(3),dp(3),dp(3),dp(3));listOf("⌂" to "Home","⌕" to "Search","▣" to "Library","≋" to "EQ").forEachIndexed{i,x->val v=LinearLayout(this@FinalPlayerActivity).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setOnClickListener{when(i){0->home();1->search();2->library();3->eq()}}};v.addView(t(x.first,18f,if(i==0)violet else muted,true).apply{gravity=Gravity.CENTER});v.addView(t(x.second,9f,if(i==0)violet else muted,true).apply{gravity=Gravity.CENTER;setPadding(0,dp(3),0,0)});addView(v,LinearLayout.LayoutParams(0,-1,1f))}}
    private fun mini()=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;background=box(card,17,true);setPadding(dp(7),dp(6),dp(7),dp(6));addView(t("◉",21f,Color.WHITE,true).apply{gravity=Gravity.CENTER;background=grad(12)},LinearLayout.LayoutParams(dp(48),dp(48)));val i=LinearLayout(this@FinalPlayerActivity).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER_VERTICAL;setPadding(dp(10),0,dp(5),0);setOnClickListener{player()}};miniTitle=t(PlaybackController.currentTitle().ifBlank{"Nothing playing"},12.5f,white,true);miniArtist=t(PlaybackController.currentArtist().ifBlank{"Choose a song"},10f,muted);i.addView(miniTitle);i.addView(miniArtist.apply{setPadding(0,dp(4),0,0)});addView(i,LinearLayout.LayoutParams(0,-1,1f));addView(t("♥",20f,muted).apply{gravity=Gravity.CENTER},LinearLayout.LayoutParams(dp(40),dp(48)));miniPlay=t(if(PlaybackController.isPlaying())"Ⅱ" else "▶",18f,white,true).apply{gravity=Gravity.CENTER;setOnClickListener{PlaybackController.toggle();refreshMini()}};addView(miniPlay,LinearLayout.LayoutParams(dp(44),dp(48)))}
    private fun refreshMini(){miniTitle.text=PlaybackController.currentTitle().ifBlank{"Nothing playing"};miniArtist.text=PlaybackController.currentArtist().ifBlank{"Choose a song"};miniPlay.text=if(PlaybackController.isPlaying())"Ⅱ" else "▶"}
    private fun page(c:LinearLayout){val s=ScrollView(this).apply{setBackgroundColor(black);isFillViewport=true};s.addView(c,FrameLayout.LayoutParams(-1,-1));page.removeAllViews();page.addView(s,FrameLayout.LayoutParams(-1,-1))}
    private fun col()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(14),dp(7),dp(14),dp(28))}
    private fun section(c:LinearLayout,s:String){c.addView(t(s,14f,white,true).apply{setPadding(0,dp(15),0,dp(9))})}
    private fun home(){val c=col();c.addView(t("Good evening",11f,muted));c.addView(t("Your sound. Your space.",25f,white,true).apply{setPadding(0,dp(5),0,dp(14))});val h=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;background=grad(22);setPadding(dp(14),dp(13),dp(12),dp(13))};h.addView(t("◉",51f,Color.WHITE,true).apply{gravity=Gravity.CENTER;background=box(Color.rgb(53,35,112),17)},LinearLayout.LayoutParams(dp(106),dp(106)));val x=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(13),0,0,0)};x.addView(t("YOUR LIBRARY",9f,Color.WHITE,true));x.addView(t(if(local.isEmpty())"Add your music" else local.first().title,17f,Color.WHITE,true).apply{setPadding(0,dp(7),0,dp(4));maxLines=1});x.addView(t(if(local.isEmpty())"Local music on this device" else local.first().artist,10f,Color.rgb(224,216,255)).apply{setPadding(0,0,0,dp(10))});x.addView(t("  PLAY NOW  ",10f,violet,true).apply{gravity=Gravity.CENTER;background=box(Color.WHITE,14);setPadding(dp(4),dp(8),dp(4),dp(8));setOnClickListener{if(local.isNotEmpty())playLocal(0)}});h.addView(x,LinearLayout.LayoutParams(0,-2,1f));c.addView(h,LinearLayout.LayoutParams(-1,dp(132)));section(c,"Recently played");local.take(10).forEachIndexed{n,tr->row(c,tr,n)};section(c,"Quick actions");val q=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};action(q,"♥","Liked"){favorites()};action(q,"▤","Playlists"){playlists()};action(q,"◷","Timer"){timerDialog()};c.addView(q,LinearLayout.LayoutParams(-1,dp(84)));page(c)}
    private fun action(p:LinearLayout,i:String,s:String,a:()->Unit){val v=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;background=box(card,15,true);setOnClickListener{a()}};v.addView(t(i,21f,violet,true));v.addView(t(s,9f,muted,true).apply{setPadding(0,dp(4),0,0)});p.addView(v,LinearLayout.LayoutParams(0,-1,1f).apply{setMargins(dp(3),0,dp(3),0)})}
    private fun row(p:LinearLayout,tr:LocalTrack,index:Int){val r=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;background=box(card,14,true);setPadding(dp(7),dp(6),dp(7),dp(6));setOnClickListener{playLocal(index)}};val art=ImageView(this);art.scaleType=ImageView.ScaleType.CENTER_CROP;art.background=grad(11);art.setImageBitmap(ArtworkResolver.load(this,tr.albumId,128));r.addView(art,LinearLayout.LayoutParams(dp(46),dp(46)));val x=LinearLayout(this@FinalPlayerActivity).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(5),0)};x.addView(t(tr.title,12f,white,true).apply{maxLines=1;ellipsize=android.text.TextUtils.TruncateAt.END});x.addView(t(tr.artist,9.5f,muted).apply{setPadding(0,dp(4),0,0)});r.addView(x,LinearLayout.LayoutParams(0,-2,1f));r.addView(t("▶",12f,violet,true));p.addView(r,LinearLayout.LayoutParams(-1,dp(62)).apply{bottomMargin=dp(6)})}
    private fun playLocal(i:Int){if(local.isEmpty())return;PlaybackController.playTracks(local,i);refreshMini()}
    private fun search(){val c=col();c.addView(t("Search",26f,white,true).apply{setPadding(0,dp(5),0,dp(12))});val e=EditText(this).apply{hint="Search songs, artists, albums";setHintTextColor(muted);setTextColor(white);textSize=14f;singleLine=true;background=box(card2,16,true);setPadding(dp(14),0,dp(14),0);setText(searchText)};c.addView(e,LinearLayout.LayoutParams(-1,dp(52)));val out=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};c.addView(out);fun run(q:String){searchText=q;if(q.length<2){out.removeAllViews();out.addView(t("Type at least 2 characters",11f,muted).apply{setPadding(0,dp(16),0,0)});return};out.removeAllViews();out.addView(t("Searching YouTube…",11f,muted).apply{setPadding(0,dp(16),0,dp(8))});Thread{try{val u="https://spotifusion.onrender.com/api/search?query="+URLEncoder.encode(q,"UTF-8")+"&limit=30";val conn=URL(u).openConnection() as HttpURLConnection;conn.connectTimeout=10000;conn.readTimeout=15000;val json=JSONObject(conn.inputStream.bufferedReader().use{it.readText()});val a=json.optJSONArray("results");ui.post{out.removeAllViews();if(a==null||a.length()==0)out.addView(t("No online results",11f,muted));else for(k in 0 until a.length()){val o=a.getJSONObject(k);onlineRow(out,o)}}}catch(ex:Exception){ui.post{out.removeAllViews();out.addView(t("Online search unavailable. Local music is still available.",11f,muted))}}}.start()};e.addTextChangedListener{run(e.text.toString().trim())};page(c)}
    private fun onlineRow(p:LinearLayout,o:JSONObject){val id=o.optString("videoId");val r=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;background=box(card,14,true);setPadding(dp(7),dp(6),dp(7),dp(6));setOnClickListener{streamOnline(id,o.optString("title"),o.optString("artist"),o.optString("thumbnail"))}};val im=ImageView(this);im.scaleType=ImageView.ScaleType.CENTER_CROP;im.background=grad(11);r.addView(im,LinearLayout.LayoutParams(dp(52),dp(52)));loadImage(im,o.optString("thumbnail"));val x=LinearLayout(this@FinalPlayerActivity).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(10),0,dp(5),0)};x.addView(t(o.optString("title","Unknown"),12f,white,true).apply{maxLines=1;ellipsize=android.text.TextUtils.TruncateAt.END});x.addView(t(o.optString("artist","Unknown Artist"),9.5f,muted).apply{setPadding(0,dp(4),0,0)});r.addView(x,LinearLayout.LayoutParams(0,-2,1f));r.addView(t("▶",12f,violet,true));p.addView(r,LinearLayout.LayoutParams(-1,dp(68)).apply{bottomMargin=dp(6)})}
    private fun loadImage(v:ImageView,u:String){if(u.isBlank())return;Thread{try{val b=BitmapFactory.decodeStream(URL(u).openStream());ui.post{v.setImageBitmap(b)}}catch(_:Exception){}}.start()}
    private fun streamOnline(id:String,title:String,artist:String,thumb:String){if(id.isBlank())return;Thread{try{val u="https://spotifusion.onrender.com/api/stream/$id";val c=URL(u).openConnection() as HttpURLConnection;c.connectTimeout=10000;c.readTimeout=15000;val o=JSONObject(c.inputStream.bufferedReader().use{it.readText()});val stream=o.optString("url");ui.post{if(stream.isBlank())toast("Stream unavailable")else{PlaybackController.play(stream,title,artist,"YouTube",id);refreshMini();toast("Playing online")}}}catch(_:Exception){ui.post{toast("Online stream unavailable")}}}.start()}
    private fun library(){val c=col();c.addView(t("Library",26f,white,true));libraryCard(c,"Local Music","${local.size} tracks","♫"){home()};libraryCard(c,"Favorites","Saved locally","♥"){favorites()};libraryCard(c,"Playlists","Create and manage","▤"){playlists()};libraryCard(c,"Downloads","Use the download action from online tracks","⇩"){toast("Downloads use Android Download Manager")};page(c)}
    private fun libraryCard(c:LinearLayout,a:String,b:String,i:String,click:()->Unit){val r=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL;background=box(card,17,true);setPadding(dp(12),dp(10),dp(12),dp(10));setOnClickListener{click()}};r.addView(t(i,22f,violet,true).apply{gravity=Gravity.CENTER;background=box(Color.rgb(29,22,48),13)},LinearLayout.LayoutParams(dp(48),dp(48)));val x=LinearLayout(this@FinalPlayerActivity).apply{orientation=LinearLayout.VERTICAL;setPadding(dp(11),0,0,0)};x.addView(t(a,12.5f,white,true));x.addView(t(b,9.5f,muted).apply{setPadding(0,dp(5),0,0)});r.addView(x,LinearLayout.LayoutParams(0,-2,1f));r.addView(t("›",23f,muted));c.addView(r,LinearLayout.LayoutParams(-1,dp(72)).apply{bottomMargin=dp(8)})}
    private fun favorites(){val c=col();c.addView(t("Liked songs",25f,white,true));c.addView(t("Favorites are stored only on this device",10f,muted).apply{setPadding(0,dp(5),0,dp(12))});local.forEachIndexed{n,tr->row(c,tr,n)};page(c)}
    private fun playlists(){val c=col();c.addView(t("Playlists",25f,white,true));c.addView(t("+ Create playlist",12f,violet,true).apply{gravity=Gravity.CENTER_VERTICAL;background=box(card2,15,true);setPadding(dp(14),0,dp(14),0);setOnClickListener{toast("Use the existing Playlist manager for full editing")}},LinearLayout.LayoutParams(-1,dp(48)).apply{bottomMargin=dp(10)});toast("Playlist data remains available in the existing manager");page(c)}
    private fun player(){val c=col();c.gravity=Gravity.CENTER_HORIZONTAL;c.addView(t("NOW PLAYING",10f,violet,true));val art=ImageView(this);art.scaleType=ImageView.ScaleType.CENTER_CROP;art.background=grad(25);val cur=local.firstOrNull{it.id.toString()==PlaybackController.currentMediaId()};art.setImageBitmap(cur?.let{ArtworkResolver.load(this,it.albumId,512)});c.addView(art,LinearLayout.LayoutParams(dp(250),dp(250)));c.addView(t(PlaybackController.currentTitle().ifBlank{"Nothing playing"},22f,white,true).apply{gravity=Gravity.CENTER;setPadding(0,dp(17),0,dp(4))});c.addView(t(PlaybackController.currentArtist().ifBlank{"Select a track"},12f,muted));val seek=SeekBar(this).apply{max=1000;progressTintList=android.content.res.ColorStateList.valueOf(violet);setOnSeekBarChangeListener(object:SeekBar.OnSeekBarChangeListener{override fun onProgressChanged(s:SeekBar?,p:Int,u:Boolean){if(u)PlaybackController.seek((PlaybackController.duration()*p/1000f).toLong())};override fun onStartTrackingTouch(s:SeekBar?){ };override fun onStopTrackingTouch(s:SeekBar?){}})};c.addView(seek,LinearLayout.LayoutParams(-1,dp(42)));val controls=LinearLayout(this).apply{gravity=Gravity.CENTER};controls.addView(t("↶",25f,white,true).apply{setOnClickListener{PlaybackController.previous()}},LinearLayout.LayoutParams(dp(65),dp(60)));controls.addView(t(if(PlaybackController.isPlaying())"Ⅱ" else "▶",30f,Color.WHITE,true).apply{gravity=Gravity.CENTER;background=grad(60);setOnClickListener{PlaybackController.toggle();player();refreshMini()}},LinearLayout.LayoutParams(dp(70),dp(70)));controls.addView(t("↷",25f,white,true).apply{setOnClickListener{PlaybackController.next()}},LinearLayout.LayoutParams(dp(65),dp(60)));c.addView(controls);val opts=LinearLayout(this).apply{gravity=Gravity.CENTER};opts.addView(t(if(PlaybackController.isShuffleEnabled())"SHUFFLE ON" else "SHUFFLE",10f,if(PlaybackController.isShuffleEnabled())violet else muted,true).apply{setOnClickListener{PlaybackController.setShuffle(!PlaybackController.isShuffleEnabled());player()}},LinearLayout.LayoutParams(0,dp(48),1f));opts.addView(t("LYRICS",10f,muted,true).apply{setOnClickListener{startActivity(android.content.Intent(this@FinalPlayerActivity,LyricsActivity::class.java))}},LinearLayout.LayoutParams(0,dp(48),1f));opts.addView(t("TIMER",10f,muted,true).apply{setOnClickListener{timerDialog()}},LinearLayout.LayoutParams(0,dp(48),1f));c.addView(opts);page(c);ui.postDelayed({if(page.childCount>0&&seek.parent!=null)seek.progress=if(PlaybackController.duration()>0)(PlaybackController.position()*1000/PlaybackController.duration()).toInt()else 0},250)}
    private fun eq(){val c=col();c.addView(t("Equalizer",26f,white,true));c.addView(t("Playback effect controls",10f,muted).apply{setPadding(0,dp(4),0,dp(12))});listOf("60 Hz","230 Hz","910 Hz","3.6 kHz","14 kHz").forEach{f->val r=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};r.addView(t(f,10f,muted),LinearLayout.LayoutParams(dp(62),-2));val s=SeekBar(this).apply{progress=55;progressTintList=android.content.res.ColorStateList.valueOf(violet);thumbTintList=android.content.res.ColorStateList.valueOf(violet)};r.addView(s,LinearLayout.LayoutParams(0,dp(45),1f));c.addView(r)};c.addView(t("PRESETS",12f,white,true).apply{setPadding(0,dp(18),0,dp(8))});listOf("Flat","Bass Boost","Vocal","Acoustic","Electronic").forEach{p->c.addView(t(p,11f,muted,true).apply{gravity=Gravity.CENTER_VERTICAL;background=box(card,14,true);setPadding(dp(14),0,0,0);setOnClickListener{toast("Preset: $p")}},LinearLayout.LayoutParams(-1,dp(46)).apply{bottomMargin=dp(6)})};page(c)}
    private fun settings(){val c=col();c.addView(t("Settings",26f,white,true));libraryCard(c,"Audio","Background playback and media controls","♫"){toast("Media3 background playback is enabled")};libraryCard(c,"Appearance","AMOLED violet theme","◐"){toast("AMOLED theme is active")};libraryCard(c,"Storage","Local files stay on this device","▣"){toast("No local audio is uploaded")};libraryCard(c,"About","Spotifusion 1.2","i"){toast("Spotifusion")};page(c)}
    private fun timerDialog(){val names=arrayOf("Off","15 minutes","30 minutes","60 minutes","90 minutes");android.app.AlertDialog.Builder(this).setTitle("Sleep timer").setItems(names){_,which->sleep?.let{ui.removeCallbacks(it)};if(which>0){val mins=intArrayOf(0,15,30,60,90)[which];sleep=Runnable{PlaybackController.pause();toast("Sleep timer ended")};ui.postDelayed(sleep!!,mins*60_000L);toast("Timer set for $mins minutes") }else toast("Timer off")}.show()}
    override fun onResume(){super.onResume();if(::miniTitle.isInitialized)refreshMini()}
    private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_SHORT).show()
}
